name: Deploy frontend to Hostinger (SFTP)

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-hostinger.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # Optional: set this in repo secrets if your API is hosted elsewhere
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Deploy via SFTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          protocol: sftp
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          port: 22
          private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}
          local-dir: frontend/dist/
          server-dir: ${{ secrets.HOSTINGER_REMOTE_DIR }}
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**

